site_name: Danfoss
site_description: Danfoss cookiecutter
site_favicon: favicon.ico
repo_url: https://github.com/drivendata/cookiecutter-data-science
edit_uri: edit/master/docs/docs
copyright: Danfoss
google_analytics: 
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
